/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.view;

import br.com.control.Tipo;
import br.com.model.ManterTipo;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author karol
 */
public class TelaMenuTipo extends javax.swing.JFrame {

    Tipo t = new Tipo();
    ManterTipo dao = new ManterTipo();

    public TelaMenuTipo() {
        initComponents();
        ListarPesquisaTipo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTregistrarNomeTipo = new javax.swing.JTextField();
        jBregistrarTipo = new javax.swing.JButton();
        jBdeletarTipo = new javax.swing.JButton();
        jBatualizarLista = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTdeletarTipo = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTslterarIdTipo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTalterarNomeTipo = new javax.swing.JTextField();
        jBalterarTipo = new javax.swing.JButton();
        jBpesquisarTipo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(239, 238, 221));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Menu Tipo");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jBregistrarTipo.setText("Registrar");
        jBregistrarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBregistrarTipoActionPerformed(evt);
            }
        });

        jBdeletarTipo.setText("Deletar");
        jBdeletarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBdeletarTipoActionPerformed(evt);
            }
        });

        jBatualizarLista.setText("Altualizar");
        jBatualizarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBatualizarListaActionPerformed(evt);
            }
        });

        jLabel2.setText("Digite o nome da Tipo :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Registrar Tipo");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Deletar Tipo ");

        jLabel5.setText("Digite o Id da Tipo :");

        jButton4.setText("Voltar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Alterar Tipo");

        jLabel7.setText("Digite o Id que deseja alterar :");

        jLabel8.setText("Nome :");

        jBalterarTipo.setText("Alterar");
        jBalterarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBalterarTipoActionPerformed(evt);
            }
        });

        jBpesquisarTipo.setText("Pesquisar");
        jBpesquisarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBpesquisarTipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jBdeletarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBatualizarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton4)
                                    .addGap(174, 174, 174)
                                    .addComponent(jLabel1))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(119, 119, 119)
                                            .addComponent(jBregistrarTipo))
                                        .addComponent(jLabel4))
                                    .addGap(202, 202, 202)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jBpesquisarTipo)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jBalterarTipo))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTalterarNomeTipo))
                                        .addComponent(jLabel6)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTslterarIdTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTdeletarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTregistrarNomeTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTregistrarNomeTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTslterarIdTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTalterarNomeTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBregistrarTipo)
                    .addComponent(jLabel8))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTdeletarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBalterarTipo)
                            .addComponent(jBpesquisarTipo))))
                .addComponent(jBdeletarTipo)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBatualizarLista)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBregistrarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBregistrarTipoActionPerformed
        // TODO add your handling code here:
        RegistrarTipo();

    }//GEN-LAST:event_jBregistrarTipoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        TelaBoasVindas Principal = new TelaBoasVindas();
        Principal.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jBatualizarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBatualizarListaActionPerformed
        // TODO add your handling code here:
           ListarPesquisaTipo();
    }//GEN-LAST:event_jBatualizarListaActionPerformed

    private void jBdeletarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBdeletarTipoActionPerformed
        // TODO add your handling code here:
        DeletarTipo();
    }//GEN-LAST:event_jBdeletarTipoActionPerformed

    private void jBpesquisarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBpesquisarTipoActionPerformed
        // TODO add your handling code here:
        PesquisarTipo();
    }//GEN-LAST:event_jBpesquisarTipoActionPerformed

    private void jBalterarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBalterarTipoActionPerformed
        // TODO add your handling code here:
        AlterarTipo();
        jTslterarIdTipo.setEditable(true);
    }//GEN-LAST:event_jBalterarTipoActionPerformed

    public void ListarPesquisaTipo() {
        try {

            DefaultTableModel consulta = (DefaultTableModel) jTable1.getModel();
            consulta.setNumRows(0);

            ArrayList<Tipo> tipo = dao.PesquisarTudo();

            for (int i = 0; i < tipo.size(); i++) {
                t = tipo.get(i);
                consulta.addRow(new Object[]{
                    tipo.get(i).getId(),
                    tipo.get(i).getNome_tipo()
                });
            }
        } catch (Exception e) {
            System.out.println("Erro ListarPesquisaTipo :" + e.getMessage());
        }
    }
    
    public void DeletarTipo(){
        t.setId(Integer.valueOf(jTdeletarTipo.getText()));
        jTdeletarTipo.setText("");

        try {
            dao.deletar(t);
        } catch (Exception e) {
            System.out.println("Erro DeletarTipo :" + e.getMessage());
        }
    }
    
    public void RegistrarTipo(){
        t.setNome_tipo(jTregistrarNomeTipo.getText());
        jTregistrarNomeTipo.setText("");

        try {
            dao.inserir(t);
        } catch (Exception e) {
            System.out.println("Erro RegistrarRegiaoTipo :" + e.getMessage());
        }
    }
    
    public void PesquisarTipo() {
        try {
            t.setId(Integer.valueOf(jTslterarIdTipo.getText()));
            dao.PesquisarRegistroTipo(t);
            JOptionPane.showMessageDialog(null, t.getNome_tipo());
            jTalterarNomeTipo.setText(t.getNome_tipo());
            jTslterarIdTipo.setEditable(false);

        } catch (Exception e) {
            System.out.println("Erro PesquisarRegiaoTipo :" + e.getMessage());
        }
        
    }

    public void AlterarTipo() {
        try {

            t.setId(Integer.valueOf(jTslterarIdTipo.getText()));
            t.setNome_tipo(jTalterarNomeTipo.getText());
            dao.EditarTipo(t);

            jTalterarNomeTipo.setText("");
            jTslterarIdTipo.setText("");
            jTslterarIdTipo.requestFocus();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro de AlterarRegiaoTipo: " + e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenuTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenuTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenuTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenuTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenuTipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBalterarTipo;
    private javax.swing.JButton jBatualizarLista;
    private javax.swing.JButton jBdeletarTipo;
    private javax.swing.JButton jBpesquisarTipo;
    private javax.swing.JButton jBregistrarTipo;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTalterarNomeTipo;
    private javax.swing.JTextField jTdeletarTipo;
    private javax.swing.JTextField jTregistrarNomeTipo;
    private javax.swing.JTextField jTslterarIdTipo;
    // End of variables declaration//GEN-END:variables
}
