/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.view;

import br.com.control.Movimento;
import br.com.model.ManterMovimento;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author karol
 */
public class TelaMenuMovimento extends javax.swing.JFrame {

    Vector<Integer> id_Tipo = new Vector<Integer>();
    Movimento m = new Movimento();
    ManterMovimento dao = new ManterMovimento();

    public TelaMenuMovimento() {
        initComponents();
        ListarPesquisaMovimento();
        RestaurarDadosComboTipo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTRegistrarNomeMovimento = new javax.swing.JTextField();
        jBregistrarTipo = new javax.swing.JButton();
        jBdeletarTipo = new javax.swing.JButton();
        jBatualizarLista = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTdeletarTipo = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTAlterarIdTipo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTAlterarNomeMovimento = new javax.swing.JTextField();
        jBalterarTipo = new javax.swing.JButton();
        jBpesquisarTipo = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jCRegistrarTipoMovimento = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jTRegistrarDescricaoMovimento = new javax.swing.JTextField();
        jTRgistrarDanoMovimento = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jCAlterarTipoMovimento = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTAlterarDescricaoMovimento = new javax.swing.JTextArea();
        jTAlterarDanoMovimento = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(239, 238, 221));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Menu Movimentos");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Dano", "Descricao", "Tipo"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jBregistrarTipo.setText("Registrar");
        jBregistrarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBregistrarTipoActionPerformed(evt);
            }
        });

        jBdeletarTipo.setText("Deletar");
        jBdeletarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBdeletarTipoActionPerformed(evt);
            }
        });

        jBatualizarLista.setText("Altualizar");
        jBatualizarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBatualizarListaActionPerformed(evt);
            }
        });

        jLabel2.setText("Digite o nome da movimento :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Registrar Movimentos");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Deletar Movimento ");

        jLabel5.setText("Digite o Id da Movimento:");

        jButton4.setText("Voltar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Alterar Movimento");

        jLabel7.setText("Digite o Id que deseja alterar :");

        jLabel8.setText("Nome :");

        jBalterarTipo.setText("Alterar");
        jBalterarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBalterarTipoActionPerformed(evt);
            }
        });

        jBpesquisarTipo.setText("Pesquisar");
        jBpesquisarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBpesquisarTipoActionPerformed(evt);
            }
        });

        jLabel9.setText("Digite o dano do movimento :");

        jLabel10.setText("Digite a descricao do movimento :");

        jCRegistrarTipoMovimento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        jCRegistrarTipoMovimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCRegistrarTipoMovimentoActionPerformed(evt);
            }
        });

        jLabel11.setText("Selecione o tipo do movimento :");

        jLabel12.setText("Dano :");

        jLabel13.setText("Descricao:");

        jLabel14.setText("Tipo :");

        jCAlterarTipoMovimento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));

        jTAlterarDescricaoMovimento.setColumns(20);
        jTAlterarDescricaoMovimento.setRows(5);
        jScrollPane2.setViewportView(jTAlterarDescricaoMovimento);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jBregistrarTipo))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTRegistrarNomeMovimento, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel9)
                                .addComponent(jLabel11))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCRegistrarTipoMovimento, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTRgistrarDanoMovimento, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTRegistrarDescricaoMovimento))))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jBdeletarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTdeletarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(267, 267, 267)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(116, 116, 116))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel7))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(101, 101, 101)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel12)
                                        .addComponent(jBpesquisarTipo))
                                    .addGap(6, 6, 6))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTAlterarNomeMovimento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTAlterarIdTipo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBalterarTipo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCAlterarTipoMovimento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTAlterarDanoMovimento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBatualizarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1041, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 275, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTRegistrarNomeMovimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jTRgistrarDanoMovimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jTRegistrarDescricaoMovimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCRegistrarTipoMovimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jTdeletarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jBdeletarTipo)))
                        .addGap(18, 18, 18)
                        .addComponent(jBregistrarTipo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13)
                                .addGap(70, 70, 70))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jTAlterarIdTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTAlterarNomeMovimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTAlterarDanoMovimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCAlterarTipoMovimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBpesquisarTipo)
                            .addComponent(jBalterarTipo))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBatualizarLista)
                .addGap(62, 62, 62))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBregistrarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBregistrarTipoActionPerformed
        // TODO add your handling code here:
        RegistrarMovimento();

    }//GEN-LAST:event_jBregistrarTipoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        TelaBoasVindas Principal = new TelaBoasVindas();
        Principal.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jBatualizarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBatualizarListaActionPerformed
        // TODO add your handling code here:
        ListarPesquisaMovimento();
    }//GEN-LAST:event_jBatualizarListaActionPerformed

    private void jBdeletarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBdeletarTipoActionPerformed
        // TODO add your handling code here:
        DeletarMovimento();
    }//GEN-LAST:event_jBdeletarTipoActionPerformed

    private void jBpesquisarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBpesquisarTipoActionPerformed
        // TODO add your handling code here:
        PesquisarMovimento();
    }//GEN-LAST:event_jBpesquisarTipoActionPerformed

    private void jBalterarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBalterarTipoActionPerformed
        // TODO add your handling code here:
        AlterarMovimento();
        jTAlterarIdTipo.setEditable(true);
    }//GEN-LAST:event_jBalterarTipoActionPerformed

    private void jCRegistrarTipoMovimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCRegistrarTipoMovimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCRegistrarTipoMovimentoActionPerformed

    public void RestaurarDadosComboTipo() {
        try {
            ResultSet rs = dao.comboBoxTipo();

            while (rs.next()) {
                id_Tipo.addElement(rs.getInt(1));
                jCRegistrarTipoMovimento.addItem(rs.getString(2));
                jCAlterarTipoMovimento.addItem(rs.getString(2));
            }

        } catch (Exception e) {
            System.out.println("Erro restaurarDadosComboTipo :" + e.getMessage());
        }

    }
    public void ListarPesquisaMovimento() {
        try {

            DefaultTableModel consulta = (DefaultTableModel) jTable1.getModel();
            consulta.setNumRows(0);

            ArrayList<Movimento> movimento = dao.PesquisarTudoMovimento();

            for (int i = 0; i < movimento.size(); i++) {
                m = movimento.get(i);
                consulta.addRow(new Object[]{
                    movimento.get(i).getId(),
                    movimento.get(i).getNome(),
                    movimento.get(i).getDano(),
                    movimento.get(i).getDescricao(),
                    movimento.get(i).getNome_tipo(),});
            }
        } catch (Exception e) {
            System.out.println("Erro ListarPesquisaMovimento :" + e.getMessage());
        }
    }

    public void DeletarMovimento() {
        m.setId(Integer.valueOf(jTdeletarTipo.getText()));
        jTdeletarTipo.setText("");

        try {
            dao.deletar(m);
        } catch (Exception e) {
            System.out.println("Erro DeletarMovimento :" + e.getMessage());
        }
    }

    public void RegistrarMovimento() {
        int codtipo ;
        
        codtipo = id_Tipo.get(jCRegistrarTipoMovimento.getSelectedIndex() - 1);
        
        m.setNome(jTRegistrarNomeMovimento.getText());
        m.setDano(Integer.valueOf(jTRgistrarDanoMovimento.getText()));
        m.setDescricao(jTRegistrarDescricaoMovimento.getText());
        m.setId_tipo(codtipo);
        jTRegistrarDescricaoMovimento.setText("");
        jTRgistrarDanoMovimento.setText("");
        jTRegistrarNomeMovimento.setText("");

        try {
            dao.inserir(m);
        } catch (Exception e) {
            System.out.println("Erro RegistrarMovimento :" + e.getMessage());
        }
    }

    public void PesquisarMovimento() {
        try {
            m.setId(Integer.valueOf(jTAlterarIdTipo.getText()));
            dao.PesquisarRegistroMovimento(m);
            JOptionPane.showMessageDialog(null, m.getNome());
            jTAlterarNomeMovimento.setText(m.getNome());
            jTAlterarDanoMovimento.setText(String.valueOf(m.getDano()));
            jTAlterarDescricaoMovimento.setText(m.getDescricao());
            jTAlterarIdTipo.setEditable(false);

        } catch (Exception e) {
            System.out.println("Erro PesquisarMovimento :" + e.getMessage());
        }

    }

    public void AlterarMovimento() {
        try {

            m.setId(Integer.valueOf(jTAlterarIdTipo.getText()));
            m.setNome(jTAlterarNomeMovimento.getText());
            m.setDano(Integer.valueOf(jTAlterarDanoMovimento.getText()));
            m.setDescricao(jTAlterarDescricaoMovimento.getText());
            dao.EditarMovimento(m);

            jTAlterarNomeMovimento.setText("");
            jTAlterarDanoMovimento.setText("");
            jTAlterarDescricaoMovimento.setText("");
            jTAlterarIdTipo.setText("");
            jTAlterarIdTipo.requestFocus();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro de AlterarMovimento: " + e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenuMovimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenuMovimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenuMovimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenuMovimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenuMovimento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBalterarTipo;
    private javax.swing.JButton jBatualizarLista;
    private javax.swing.JButton jBdeletarTipo;
    private javax.swing.JButton jBpesquisarTipo;
    private javax.swing.JButton jBregistrarTipo;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jCAlterarTipoMovimento;
    private javax.swing.JComboBox<String> jCRegistrarTipoMovimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTAlterarDanoMovimento;
    private javax.swing.JTextArea jTAlterarDescricaoMovimento;
    private javax.swing.JTextField jTAlterarIdTipo;
    private javax.swing.JTextField jTAlterarNomeMovimento;
    private javax.swing.JTextField jTRegistrarDescricaoMovimento;
    private javax.swing.JTextField jTRegistrarNomeMovimento;
    private javax.swing.JTextField jTRgistrarDanoMovimento;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTdeletarTipo;
    // End of variables declaration//GEN-END:variables
}
